"""Editorial SEO context for phone brand landing pages."""

BRAND_SEO = {
    "Apple": ("Explore Apple iPhone models across current and recent generations with specifications, release information, pricing context and comparison-friendly details. Browse iPhone family pages to compare models before buying.", "Apple model names can represent different generations and regional configurations. Use the exact model page and cited source when checking specifications, network support and availability."),
    "Samsung": ("Browse Samsung Galaxy phones across flagship, foldable and mid-range families. Explore Galaxy S, Galaxy A and Galaxy Z model groups, then compare core specifications, release information and related phones.", "Samsung specifications can vary by region, chipset and network configuration. Check the exact Galaxy model and cited source before making a purchase decision."),
    "Google": ("Explore Google Pixel phones with key specifications, release information and family-based comparisons. Find Pixel flagship and A-series models and compare cameras, performance, battery and software features.", "Pixel availability and specifications can vary by market. Check the exact regional model, supported networks and cited source before purchase."),
    "OnePlus": ("Compare OnePlus smartphones by performance, display, camera hardware, battery and pricing context. Explore the flagship Number family and value-focused Nord models.", "OnePlus specifications and network support may vary between regional versions, especially for imported phones. Verify the exact model before buying."),
    "Xiaomi": ("Browse Xiaomi smartphones across flagship Number and T-series models, plus related Redmi and POCO catalogs. Compare performance, cameras, displays, battery and other core features.", "Xiaomi family names can cover different regional variants. Verify the exact model number, software version and supported network bands from the cited source."),
    "Redmi": ("Explore Redmi smartphones with a focus on Note and value-oriented model families. Compare display, performance, camera, battery, 5G support and pricing context across published Redmi phones.", "Redmi models and specifications can vary by market and memory configuration. Check the exact regional model and cited source before buying."),
    "POCO": ("Browse POCO smartphones built around performance, gaming value and fast charging. Explore F, X and M families and compare chipsets, displays, batteries and cameras.", "POCO names and specifications can vary by region. Verify the exact model, memory configuration and network compatibility before purchase."),
    "OPPO": ("Explore OPPO smartphones across Find and Reno families, with model-level specifications, camera details, displays, batteries and comparison-friendly information.", "OPPO specifications, naming and availability may vary by market. Use the exact model page and cited source for final verification."),
    "vivo": ("Browse vivo smartphones across X and V families with practical information on cameras, displays, performance, battery and release context. Compare related models before choosing.", "vivo model configurations can differ by region. Check the exact model and cited manufacturer or source information before purchase."),
    "realme": ("Explore realme smartphones across GT performance models and Number-series devices. Compare processors, displays, cameras, charging, battery and pricing context.", "realme specifications and regional availability can differ. Confirm the exact model and configuration from the cited source."),
    "Motorola": ("Browse Motorola smartphones across Edge, Moto G and Razr families. Compare displays, cameras, processors, battery capacity and foldable or conventional designs.", "Motorola model names and configurations can differ by market. Check the exact regional model and cited source before buying."),
    "HONOR": ("Explore HONOR smartphones across Magic and X families, comparing display technology, cameras, performance, battery and pricing context.", "HONOR specifications and availability vary by market. Verify the exact model and regional configuration from the cited source."),
    "Nothing": ("Browse Nothing Phone models with clean software, distinctive hardware design and practical specifications. Compare published models by display, chipset, camera, battery and connectivity.", "Nothing phone specifications and availability can vary by market. Check the exact model and cited source before purchase."),
    "ASUS": ("Explore ASUS smartphones including ROG Phone gaming models and Zenfone devices. Compare performance, displays, cooling-oriented hardware, cameras and battery features.", "ASUS model availability and configurations can differ by market. Verify the exact regional model and cited source before buying."),
    "Sony": ("Browse Sony Xperia smartphones with model-level information on displays, cameras, performance, battery and multimedia features. Explore Xperia family pages and related comparisons.", "Sony Xperia specifications and regional availability may vary. Check the exact model and cited source before purchase."),
    "Nokia": ("Explore published Nokia smartphones with practical specifications, release information and comparison-friendly details across the catalog.", "Nokia model availability and configurations can vary by market. Verify the exact model and cited source before purchase."),
    "Infinix": ("Browse Infinix smartphones with specifications, display, performance, camera, battery and pricing context for value-focused buyers.", "Infinix configurations can vary by market and memory option. Check the exact model and cited source before buying."),
    "Tecno": ("Explore Tecno smartphones with model-level specifications and practical comparisons across performance, display, cameras, battery and 5G connectivity.", "Tecno model names and specifications can vary by region. Verify the exact model and cited source before purchase."),
    "Huawei": ("Browse Huawei smartphones with specifications, camera and display information, release context and related comparison opportunities.", "Huawei availability, software services and regional configurations can differ. Check the exact model and cited source before buying."),
    "ZTE": ("Explore published ZTE smartphones with specifications, release information and useful comparisons across performance, display, camera and connectivity.", "ZTE specifications and availability can vary by market. Verify the exact model and cited source before purchase."),
}


def brand_seo_context(brand):
    intro, faq = BRAND_SEO.get(brand, (
        f"Browse published {brand} smartphones with specifications, release information, pricing context and useful comparisons. Explore individual models and discover related phones across the wider catalog.",
        "Phone specifications, prices and network compatibility can vary by market and configuration. Check the cited source and exact regional model before making a purchase decision.",
    ))
    return {"intro": intro, "faq": faq}
