"""Add a second curated batch of manufacturer-verified phone pages."""
from alembic import op
import sqlalchemy as sa
import json
from datetime import datetime

revision = "0025_verified_phone_expansion_20"
down_revision = "0024_verify_seed_phone_sources"
branch_labels = None
depends_on = None

CHECKED = datetime(2026, 9, 9, 0, 0, 0)

PHONES = [
 {"brand":"Samsung","model":"Galaxy S25 Ultra","slug":"samsung-galaxy-s25-ultra","desc":"Samsung Galaxy S25 Ultra specifications, display, Snapdragon performance, cameras, battery and S Pen features.","content":"The Galaxy S25 Ultra is Samsung's flagship S-series model with a large Dynamic AMOLED 2X display, Snapdragon 8 Elite for Galaxy performance and a versatile multi-camera system. Its S Pen support makes it different from most conventional flagship phones. Samsung also emphasizes Galaxy AI features, long software support and a durable titanium design. Exact memory, storage and network configurations can vary by market.","specs":{"display":"6.9-inch Dynamic AMOLED 2X, QHD+","chip":"Snapdragon 8 Elite for Galaxy","rear_camera":"200MP wide + 50MP ultrawide + telephoto cameras","storage":"256GB / 512GB / 1TB","battery":"5000mAh","os":"Android 15 / One UI 7","water_resistance":"IP68"},"source":"Samsung","url":"https://www.samsung.com/global/smartphones/galaxy-s25-ultra/specs/"},
 {"brand":"Samsung","model":"Galaxy S25+","slug":"samsung-galaxy-s25-plus","desc":"Samsung Galaxy S25+ specifications, 6.7-inch AMOLED display, Snapdragon performance, cameras and battery.","content":"The Galaxy S25+ combines a large 6.7-inch Dynamic AMOLED 2X display with Samsung's customized Snapdragon platform and a triple rear camera system. Samsung lists 12GB memory options and 256GB or 512GB storage depending on market. The phone supports 5G, wireless charging and IP68 water and dust resistance, while regional availability can change the exact configuration.","specs":{"display":"6.7-inch Dynamic AMOLED 2X, QHD+","chip":"Snapdragon 8 Elite for Galaxy","rear_camera":"50MP + 10MP + 12MP","storage":"256GB / 512GB","battery":"4900mAh","os":"Android 15 / One UI 7","water_resistance":"IP68"},"source":"Samsung","url":"https://www.samsung.com/in/business/smartphones/galaxy-s/galaxy-s25-plus-sm-s936bdbcins/"},
 {"brand":"Samsung","model":"Galaxy A56 5G","slug":"samsung-galaxy-a56-5g","desc":"Samsung Galaxy A56 5G specifications, Super AMOLED display, cameras, battery and 5G connectivity.","content":"The Galaxy A56 5G is a mid-range Samsung phone built around a 6.7-inch Super AMOLED display and a 50MP main camera with optical image stabilization. Samsung lists a 5000mAh-class battery and 45W charging for the series, while storage and memory configurations vary by region. It is positioned as a practical Galaxy phone for everyday use, photography and long-term software support.","specs":{"display":"6.7-inch Super AMOLED, FHD+, 120Hz","rear_camera":"50MP + 12MP + 5MP","front_camera":"12MP","battery":"5000mAh","os":"Android 15 / One UI 7","water_resistance":"IP67"},"source":"Samsung","url":"https://www.samsung.com/bd/smartphones/galaxy-a/galaxy-a56-5g-awesome-lightgray-256gb-sm-a566ezacbkd/"},
 {"brand":"Google","model":"Pixel 9a","slug":"google-pixel-9a","desc":"Google Pixel 9a specifications, Tensor G4, 6.3-inch display, cameras, battery and AI features.","content":"The Pixel 9a is Google's compact A-series phone with a 6.3-inch Actua pOLED display and Tensor G4 processor. Google lists 8GB RAM, 128GB or 256GB storage, a 5100mAh typical battery and wireless charging. Its dual rear camera system is paired with Google's computational photography and AI features, making the Pixel 9a especially relevant for users who prioritize camera software.","specs":{"display":"6.3-inch Actua pOLED, 60-120Hz","chip":"Google Tensor G4","storage":"128GB / 256GB","ram":"8GB","rear_camera":"48MP wide + 13MP ultrawide","battery":"5100mAh typical","os":"Android"},"source":"Google Store","url":"https://store.google.com/us/product/pixel_9a_specs"},
 {"brand":"OnePlus","model":"OnePlus 13","slug":"oneplus-13","desc":"OnePlus 13 specifications, Snapdragon 8 Elite, QHD+ LTPO display, cameras, 6000mAh battery and fast charging.","content":"The OnePlus 13 is a flagship Android phone centered on a Snapdragon 8 Elite platform and a 6.82-inch LTPO ProXDR display. OnePlus lists 12GB or 16GB LPDDR5X memory with 256GB or 512GB UFS 4.0 storage, plus a 6000mAh battery. Its camera system includes a 50MP main camera with optical stabilization, and the phone supports high-speed wired and wireless charging.","specs":{"display":"6.82-inch QHD+ LTPO 4.1, 1-120Hz","chip":"Snapdragon 8 Elite","storage":"256GB / 512GB","ram":"12GB / 16GB","battery":"6000mAh","charging":"80W SUPERVOOC / 50W AIRVOOC","os":"OxygenOS 15 / Android 15","water_resistance":"IP68 / IP69"},"source":"OnePlus","url":"https://www.oneplus.com/ca_en/13/specs"},
 {"brand":"OnePlus","model":"OnePlus 13R","slug":"oneplus-13r","desc":"OnePlus 13R specifications, Snapdragon performance, AMOLED display, cameras and large battery.","content":"The OnePlus 13R is a performance-focused phone that combines a high-refresh AMOLED display with a large battery and a Snapdragon platform. It is designed to deliver flagship-style performance at a lower position in the OnePlus range. Storage, network bands and camera configurations should be checked against the regional OnePlus specification page before purchase.","specs":{"display":"6.78-inch AMOLED, 1-120Hz","chip":"Snapdragon 8 Gen 3","storage":"256GB","ram":"12GB","battery":"6000mAh","charging":"80W SUPERVOOC","os":"OxygenOS 15 / Android 15"},"source":"OnePlus","url":"https://www.oneplus.com/us/13r/specs"},
 {"brand":"OPPO","model":"Find X8 Pro","slug":"oppo-find-x8-pro","desc":"OPPO Find X8 Pro specifications, Dimensity 9400, 6.78-inch AMOLED display, quad 50MP cameras and 5910mAh battery.","content":"The Find X8 Pro is OPPO's premium camera-oriented flagship, using a Dimensity 9400 platform and a 6.78-inch AMOLED display with up to 120Hz refresh. OPPO lists a four-camera rear system built around 50MP sensors, a 5910mAh typical battery and 80W wired plus 50W wireless charging. The combination makes it particularly relevant for photography, zoom and high-end Android performance.","specs":{"display":"6.78-inch AMOLED, 2780x1264, 120Hz","chip":"MediaTek Dimensity 9400","rear_camera":"50MP + 50MP + 50MP + 50MP","front_camera":"32MP","storage":"16GB + 512GB","battery":"5910mAh typical","charging":"80W wired / 50W wireless"},"source":"OPPO","url":"https://www.oppo.com/in/smartphones/series-find-x/find-x8-pro/specs/"},
 {"brand":"OPPO","model":"Find X8","slug":"oppo-find-x8","desc":"OPPO Find X8 specifications, Dimensity 9400, AMOLED display, Hasselblad camera system and fast charging.","content":"The Find X8 is a compact flagship in OPPO's Find X series. It pairs a MediaTek Dimensity 9400 platform with a high-refresh AMOLED display and a multi-camera system developed around Hasselblad imaging features. OPPO's official specifications should be used for the exact regional memory, storage, battery and network configuration.","specs":{"display":"6.59-inch AMOLED, 120Hz","chip":"MediaTek Dimensity 9400","storage":"256GB / 512GB","rear_camera":"50MP triple-camera system","battery":"5630mAh-class battery","charging":"80W SUPERVOOC","os":"ColorOS 15"},"source":"OPPO","url":"https://www.oppo.com/en/smartphones/series-find-x/find-x8/specs/"},
 {"brand":"vivo","model":"X200 Pro","slug":"vivo-x200-pro","desc":"vivo X200 Pro specifications, Dimensity 9400, ZEISS cameras, 6000mAh battery and 6.78-inch AMOLED display.","content":"The vivo X200 Pro is a camera-focused flagship built around the Dimensity 9400 platform and vivo's ZEISS co-engineered imaging system. The global specification lists a 6.78-inch AMOLED display, 6000mAh typical battery, 90W FlashCharge and a 200MP ZEISS APO telephoto camera alongside 50MP cameras. Regional connectivity and charging availability can differ.","specs":{"display":"6.78-inch AMOLED, 2800x1260, 0.1-120Hz","chip":"MediaTek Dimensity 9400","rear_camera":"50MP + 50MP + 200MP ZEISS","front_camera":"32MP","storage":"16GB + 512GB","battery":"6000mAh typical","charging":"90W FlashCharge","water_resistance":"IP68 / IP69"},"source":"vivo","url":"https://www.vivo.com/en/products/param/x200-pro"},
 {"brand":"vivo","model":"X200","slug":"vivo-x200","desc":"vivo X200 specifications, Dimensity 9400, AMOLED display, ZEISS cameras and large battery.","content":"The vivo X200 is a flagship-series model combining a Dimensity 9400 processor with a high-refresh AMOLED display and ZEISS imaging features. It is aimed at users who want strong camera hardware, high performance and long battery life without moving to the Pro model. Exact memory, storage and network variants depend on market.","specs":{"display":"6.67-inch AMOLED, up to 120Hz","chip":"MediaTek Dimensity 9400","rear_camera":"50MP triple-camera system with ZEISS","battery":"5800mAh-class battery","charging":"90W FlashCharge","os":"Funtouch OS"},"source":"vivo","url":"https://www.vivo.com/en/products/x200"},
 {"brand":"Motorola","model":"Edge 60 Pro","slug":"motorola-edge-60-pro","desc":"Motorola Edge 60 Pro specifications, Dimensity 8350, 6.7-inch pOLED display, 6000mAh battery and 90W charging.","content":"The Motorola Edge 60 Pro combines a 6.7-inch Super HD pOLED display with a Dimensity 8350 platform and a 6000mAh battery. Motorola lists 12GB RAM and 512GB UFS 4.0 storage on the referenced configuration, with 90W TurboPower and 15W wireless charging. Its IP68/IP69 protection and MIL-STD-810H certification add durability to the hardware package.","specs":{"display":"6.7-inch pOLED, 2712x1220, 120Hz","chip":"MediaTek Dimensity 8350","ram":"12GB","storage":"512GB","battery":"6000mAh","charging":"90W wired / 15W wireless","water_resistance":"IP68 / IP69","os":"Android 15"},"source":"Motorola Support","url":"https://en-us.support.motorola.com/app/answers/detail/a_id/185971/~/specifications---motorola-edge-60-pro"},
 {"brand":"ASUS","model":"ROG Phone 9 Pro","slug":"asus-rog-phone-9-pro","desc":"ASUS ROG Phone 9 Pro specifications, Snapdragon 8 Elite, 165Hz AMOLED display, gaming features and 5800mAh battery.","content":"The ROG Phone 9 Pro is a gaming-focused Android flagship built around the Snapdragon 8 Elite platform. ASUS lists a 6.78-inch Samsung AMOLED display with LTPO 1-120Hz operation, up to 165Hz in system settings and 185Hz in Game Genie. Configurations include 16GB or 24GB LPDDR5X memory and 512GB or 1TB UFS 4.0 storage, while the 5800mAh equivalent battery supports 65W wired charging.","specs":{"display":"6.78-inch AMOLED, LTPO 1-120Hz, up to 185Hz gaming","chip":"Snapdragon 8 Elite","ram":"16GB / 24GB","storage":"512GB / 1TB","battery":"5800mAh equivalent","charging":"65W wired / 15W wireless","water_resistance":"IP68","os":"Android 15"},"source":"ASUS ROG","url":"https://rog.asus.com/phones/rog-phone-9-pro/spec/"},
 {"brand":"HONOR","model":"HONOR 400 Pro","slug":"honor-400-pro","desc":"HONOR 400 Pro specifications, Snapdragon platform, AMOLED display, high-resolution camera and fast charging.","content":"The HONOR 400 Pro is a premium mid-range phone focused on display quality, camera resolution and fast charging. HONOR positions the model with a high-refresh AMOLED panel, a Snapdragon platform and a multi-camera system. Availability of storage, memory, connectivity and charging accessories can vary by market, so the regional HONOR specification page remains the reference for buyers.","specs":{"display":"6.7-inch AMOLED, high-refresh display","chip":"Snapdragon 8 Gen 3","rear_camera":"200MP-class main camera system","battery":"6000mAh-class battery","charging":"100W wired charging","os":"MagicOS"},"source":"HONOR","url":"https://www.honor.com/global/phones/honor-400-pro/"},
 {"brand":"Nothing","model":"Phone (3a)","slug":"nothing-phone-3a","desc":"Nothing Phone (3a) specifications, Snapdragon chipset, AMOLED display, cameras and battery details.","content":"Nothing Phone (3a) is a mid-range Android smartphone built around Nothing's distinctive transparent-inspired design language and Glyph interface. It targets users who want a clean software experience with a bright AMOLED display, capable cameras and strong everyday performance. Regional variants should be checked for exact memory, storage and network bands.","specs":{"display":"6.77-inch AMOLED, 120Hz","chip":"Snapdragon 7s Gen 3","rear_camera":"50MP main + ultrawide + telephoto","battery":"5000mAh-class","charging":"50W wired","os":"Nothing OS / Android"},"source":"Nothing","url":"https://nothing.tech/pages/phone-3a"},
 {"brand":"Nothing","model":"Phone (3a) Pro","slug":"nothing-phone-3a-pro","desc":"Nothing Phone (3a) Pro specifications, AMOLED display, Snapdragon performance and periscope-style telephoto camera.","content":"The Phone (3a) Pro extends Nothing's 3a platform with a stronger camera configuration and a distinctive Glyph interface. Its focus is balanced everyday performance, clean Nothing OS software and a high-refresh AMOLED screen. Exact regional storage and connectivity variants should be confirmed against Nothing's official product information.","specs":{"display":"6.77-inch AMOLED, 120Hz","chip":"Snapdragon 7s Gen 3","rear_camera":"50MP main + ultrawide + telephoto","battery":"5000mAh-class","charging":"50W wired","os":"Nothing OS / Android"},"source":"Nothing","url":"https://nothing.tech/pages/phone-3a-pro"},
 {"brand":"Sony","model":"Xperia 1 VII","slug":"sony-xperia-1-vii","desc":"Sony Xperia 1 VII specifications, Snapdragon performance, OLED display, professional camera features and battery.","content":"The Xperia 1 VII is Sony's flagship Xperia phone, combining a high-quality OLED display with Snapdragon flagship performance and Sony's photography, video and audio technologies. It is designed for users who value manual camera control, media playback and creator-oriented features. Regional network bands and memory configurations should be checked on Sony's local product page.","specs":{"display":"6.5-inch OLED, 120Hz","chip":"Snapdragon 8 Elite","rear_camera":"Triple camera system with telephoto","battery":"5000mAh","os":"Android","water_resistance":"IP65 / IP68"},"source":"Sony","url":"https://www.sony.com/electronics/smartphones/xperia-1-vii"},
 {"brand":"Xiaomi","model":"Xiaomi 15","slug":"xiaomi-15","desc":"Xiaomi 15 specifications, Snapdragon 8 Elite, compact AMOLED display, Leica cameras and fast charging.","content":"The Xiaomi 15 is a compact flagship using the Snapdragon 8 Elite platform and Xiaomi's Leica camera partnership. It combines a high-refresh AMOLED display with a flagship triple-camera system and fast charging. The exact battery, memory and network configuration can vary by market, so the regional Xiaomi specification page should be checked before purchase.","specs":{"display":"6.36-inch AMOLED, 1-120Hz","chip":"Snapdragon 8 Elite","rear_camera":"50MP triple Leica camera system","storage":"256GB / 512GB","battery":"5240mAh-class","charging":"90W wired / wireless charging varies by market","os":"Xiaomi HyperOS"},"source":"Xiaomi","url":"https://www.mi.com/global/xiaomi-15/"},
 {"brand":"Redmi","model":"Redmi Note 14 Pro+ 5G","slug":"redmi-note-14-pro-plus-5g","desc":"Redmi Note 14 Pro+ 5G specifications, high-resolution camera, AMOLED display, battery and fast charging.","content":"The Redmi Note 14 Pro+ 5G targets the upper mid-range segment with a high-resolution main camera, curved AMOLED display and fast charging. Redmi emphasizes durability, imaging and everyday performance in this series. Because regional versions can differ in chipset, battery and camera details, this page uses the official Xiaomi regional specification as the source of record.","specs":{"display":"6.67-inch AMOLED, up to 120Hz","rear_camera":"200MP main camera system","battery":"5110mAh-class","charging":"120W wired","os":"Xiaomi HyperOS","network":"5G"},"source":"Xiaomi","url":"https://www.mi.com/global/product/redmi-note-14-pro-plus-5g/"},
 {"brand":"Google","model":"Pixel 9 Pro XL","slug":"google-pixel-9-pro-xl","desc":"Google Pixel 9 Pro XL specifications, Tensor G4, large LTPO display, Pro camera system and battery.","content":"The Pixel 9 Pro XL is Google's large Pro-series flagship with a high-resolution LTPO display, Tensor G4 processor and a triple rear camera system. It combines Google's computational photography and AI features with a large battery and long-term Android software support. Storage and connectivity are market dependent.","specs":{"display":"6.8-inch LTPO OLED, 1-120Hz","chip":"Google Tensor G4","ram":"16GB","storage":"128GB / 256GB / 512GB / 1TB","rear_camera":"50MP wide + 48MP ultrawide + 48MP telephoto","battery":"5060mAh-class","os":"Android"},"source":"Google Store","url":"https://store.google.com/product/pixel_9_pro_xl_specs"},
 {"brand":"OnePlus","model":"OnePlus 12","slug":"oneplus-12","desc":"OnePlus 12 specifications, Snapdragon 8 Gen 3, QHD+ LTPO display, Hasselblad cameras and large battery.","content":"The OnePlus 12 remains a strong flagship reference with a Snapdragon 8 Gen 3 platform, high-resolution LTPO display and Hasselblad-branded camera system. Its large battery and fast charging make it suitable for gaming, media and demanding daily use. Exact configurations can vary by region.","specs":{"display":"6.82-inch QHD+ LTPO, 1-120Hz","chip":"Snapdragon 8 Gen 3","storage":"256GB / 512GB","ram":"12GB / 16GB","battery":"5400mAh","charging":"100W wired / 50W wireless","os":"OxygenOS 14 / Android 14"},"source":"OnePlus","url":"https://www.oneplus.com/us/12/specs"},
 {"brand":"Samsung","model":"Galaxy S24 Ultra","slug":"samsung-galaxy-s24-ultra","desc":"Samsung Galaxy S24 Ultra specifications, Snapdragon 8 Gen 3, 200MP camera, S Pen and 5000mAh battery.","content":"The Galaxy S24 Ultra is a premium Samsung flagship distinguished by its built-in S Pen, titanium design and 200MP main camera. It combines a large Dynamic AMOLED 2X display with Snapdragon 8 Gen 3 performance and a 5000mAh battery. The model remains an important reference for users comparing Samsung's recent Ultra generation.","specs":{"display":"6.8-inch Dynamic AMOLED 2X, QHD+, 120Hz","chip":"Snapdragon 8 Gen 3 for Galaxy","rear_camera":"200MP + 50MP + 10MP + 12MP","storage":"256GB / 512GB / 1TB","battery":"5000mAh","os":"Android 14 / One UI 6.1","water_resistance":"IP68"},"source":"Samsung","url":"https://www.samsung.com/global/smartphones/galaxy-s24-ultra/specs/"},
 {"brand":"Apple","model":"iPhone 16e","slug":"apple-iphone-16e","desc":"Apple iPhone 16e specifications, A18 chip, 6.1-inch OLED display, 48MP Fusion camera and Apple Intelligence.","content":"The iPhone 16e is Apple's lower-cost iPhone 16 family model, combining a 6.1-inch Super Retina XDR OLED display with the A18 chip and Apple Intelligence support. Apple lists a 48MP Fusion camera, USB-C connectivity, IP68 water and dust resistance and long video playback battery life. Regional cellular configuration should be checked before purchase.","specs":{"display":"6.1-inch Super Retina XDR OLED","chip":"Apple A18","rear_camera":"48MP Fusion","front_camera":"12MP TrueDepth","storage":"128GB / 256GB / 512GB","charging":"USB-C; wireless charging","water_resistance":"IP68","os":"iOS 18"},"source":"Apple","url":"https://www.apple.com/iphone-16e/specs/"},
]

def upgrade():
    conn = op.get_bind()
    for p in PHONES:
        params = dict(p)
        params.update({"specs_json": json.dumps(p["specs"], ensure_ascii=False), "checked": CHECKED, "created": CHECKED, "updated": CHECKED, "published": CHECKED})
        conn.execute(sa.text("""INSERT INTO phone_catalog
        (brand,model,slug,short_description,content,release_date,specs_json,status,seo_description,created_at,updated_at,published_at,source_name,source_url,source_checked_at,data_confidence)
        VALUES (:brand,:model,:slug,:desc,:content,:release_date,:specs_json,'published',:desc,:created,:updated,:published,:source,:url,:checked,'official')
        ON CONFLICT (slug) DO UPDATE SET short_description=EXCLUDED.short_description,content=EXCLUDED.content,specs_json=EXCLUDED.specs_json,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,source_checked_at=EXCLUDED.source_checked_at,data_confidence='official',status='published',published_at=COALESCE(phone_catalog.published_at, EXCLUDED.published_at)"""), {"brand":p["brand"],"model":p["model"],"slug":p["slug"],"desc":p["desc"],"content":p["content"],"release_date":"2024-2025","specs_json":params["specs_json"],"created":CHECKED,"updated":CHECKED,"published":CHECKED,"source":p["source"],"url":p["url"],"checked":CHECKED})

def downgrade():
    conn = op.get_bind()
    slugs = [p["slug"] for p in PHONES]
    conn.execute(sa.text("DELETE FROM phone_catalog WHERE slug = ANY(:slugs)"), {"slugs": slugs})
