"""Expand the global phone catalog beyond 100 published models with useful SEO copy."""
from alembic import op
import sqlalchemy as sa
import json
from datetime import datetime

revision = "0028_phone_catalog_100_plus_seo"
down_revision = "0027_phone_expansion_50_seo"
branch_labels = None
depends_on = None

CHECKED = datetime(2026, 9, 9, 0, 0, 0)

# 40 additional models. Data is intentionally model-level; regional price, bands,
# memory and color options should be confirmed from the linked manufacturer source.
RAW = [
("Apple","iPhone 15","apple-iphone-15","Apple iPhone 15 specifications, A16 Bionic, OLED display, 48MP main camera and USB-C.","The iPhone 15 combines Apple's A16 Bionic chip with a Super Retina XDR OLED display and a 48MP main camera. USB-C connectivity and Apple's iOS ecosystem make it a practical mainstream flagship-era model. Regional storage, network and feature availability should be checked with Apple.",{"chip":"Apple A16 Bionic","display":"6.1-inch Super Retina XDR OLED","rear_camera":"48MP Fusion + 12MP ultrawide","port":"USB-C","os":"iOS"},"https://www.apple.com/iphone-15/"),
("Apple","iPhone 15 Plus","apple-iphone-15-plus","Apple iPhone 15 Plus specifications, A16 Bionic, large OLED display, 48MP camera and USB-C.","The iPhone 15 Plus provides the iPhone 15 platform in a larger body, with A16 Bionic performance, a Super Retina XDR OLED display and a 48MP main camera. It is suited to buyers who prefer a larger screen while retaining the standard iPhone feature set.",{"chip":"Apple A16 Bionic","display":"6.7-inch Super Retina XDR OLED","rear_camera":"48MP + 12MP ultrawide","port":"USB-C","os":"iOS"},"https://www.apple.com/iphone-15/"),
("Apple","iPhone 15 Pro","apple-iphone-15-pro","Apple iPhone 15 Pro specifications, A17 Pro, ProMotion OLED, titanium design and USB-C.","The iPhone 15 Pro is a compact Pro model built around Apple's A17 Pro chip, a ProMotion OLED display and a titanium enclosure. Its Pro camera system and USB-C port make it relevant for photography, gaming and high-speed accessory workflows.",{"chip":"Apple A17 Pro","display":"6.1-inch Super Retina XDR OLED, ProMotion","rear_camera":"48MP + 12MP ultrawide + 12MP telephoto","port":"USB-C","os":"iOS"},"https://www.apple.com/iphone-15-pro/"),
("Apple","iPhone 15 Pro Max","apple-iphone-15-pro-max","Apple iPhone 15 Pro Max specifications, A17 Pro, 6.7-inch ProMotion OLED and 5x telephoto camera.","The iPhone 15 Pro Max pairs A17 Pro performance with a large ProMotion OLED display and titanium design. Its 5x telephoto camera, USB-C connectivity and Pro video capabilities make it a strong choice for demanding mobile photography and media use.",{"chip":"Apple A17 Pro","display":"6.7-inch Super Retina XDR OLED, ProMotion","rear_camera":"48MP + 12MP ultrawide + 12MP 5x telephoto","port":"USB-C","os":"iOS"},"https://www.apple.com/iphone-15-pro/"),
("Samsung","Galaxy S24","samsung-galaxy-s24","Samsung Galaxy S24 specifications, Dynamic AMOLED 2X, Galaxy AI, triple cameras and 4000mAh battery.","The Galaxy S24 is a compact Samsung flagship with a Dynamic AMOLED 2X display, modern Galaxy AI features and a triple-camera system. Its compact size, wireless charging support and long software-support direction make it useful for buyers comparing premium Android phones.",{"display":"6.2-inch Dynamic AMOLED 2X","chip":"Snapdragon 8 Gen 3 for Galaxy / Exynos 2400 by region","battery":"4000mAh typical","rear_camera":"50MP + 10MP telephoto + 12MP ultrawide","os":"Android / One UI"},"https://www.samsung.com/global/galaxy/galaxy-s24/specs/"),
("Samsung","Galaxy S24+","samsung-galaxy-s24-plus","Samsung Galaxy S24+ specifications, QHD+ Dynamic AMOLED 2X, Galaxy AI and 4900mAh battery.","The Galaxy S24+ expands the S24 experience with a larger high-resolution Dynamic AMOLED 2X display and a higher-capacity battery. It combines flagship processing, a versatile triple-camera system and Galaxy AI features in a larger premium Android design.",{"display":"6.7-inch Dynamic AMOLED 2X, QHD+","chip":"Snapdragon 8 Gen 3 for Galaxy / Exynos 2400 by region","battery":"4900mAh typical","rear_camera":"50MP + 10MP telephoto + 12MP ultrawide","os":"Android / One UI"},"https://www.samsung.com/global/galaxy/galaxy-s24/specs/"),
("Samsung","Galaxy S24 Ultra","samsung-galaxy-s24-ultra","Samsung Galaxy S24 Ultra specifications, Snapdragon 8 Gen 3 for Galaxy, 200MP camera and S Pen.","The Galaxy S24 Ultra is Samsung's premium S-series model, combining a large QHD+ Dynamic AMOLED 2X display, Snapdragon 8 Gen 3 for Galaxy and an integrated S Pen. Its 200MP main camera and multiple telephoto cameras target photography, productivity and power users.",{"display":"6.8-inch QHD+ Dynamic AMOLED 2X","chip":"Snapdragon 8 Gen 3 for Galaxy","rear_camera":"200MP + 50MP 5x telephoto + 10MP 3x telephoto + 12MP ultrawide","battery":"5000mAh","os":"Android / One UI"},"https://www.samsung.com/global/galaxy/galaxy-s24/specs/"),
("Samsung","Galaxy A55 5G","samsung-galaxy-a55-5g","Samsung Galaxy A55 5G specifications, Super AMOLED display, Exynos 1480 and 5000mAh battery.","The Galaxy A55 5G is a mid-range Samsung phone focused on display quality, battery life and 5G connectivity. Its Super AMOLED panel, Exynos 1480 platform and multi-camera setup make it a useful benchmark against other affordable premium Android phones.",{"display":"6.6-inch Super AMOLED, 120Hz","chip":"Exynos 1480","battery":"5000mAh","rear_camera":"50MP + 12MP ultrawide + 5MP macro","os":"Android / One UI"},"https://www.samsung.com/global/smartphones/galaxy-a55-5g/specs/"),
("Samsung","Galaxy A35 5G","samsung-galaxy-a35-5g","Samsung Galaxy A35 5G specifications, Super AMOLED 120Hz display, Exynos 1380 and 5000mAh battery.","The Galaxy A35 5G targets mid-range buyers with a large 120Hz Super AMOLED display, 5G connectivity and a 5000mAh battery. Samsung's One UI software and multi-camera hardware provide a familiar all-round Android experience.",{"display":"6.6-inch Super AMOLED, 120Hz","chip":"Exynos 1380","battery":"5000mAh","rear_camera":"50MP + 8MP ultrawide + 5MP macro","os":"Android / One UI"},"https://www.samsung.com/global/smartphones/galaxy-a35-5g/specs/"),
("Google","Pixel 8","google-pixel-8","Google Pixel 8 specifications, Tensor G3, 6.2-inch OLED display and advanced computational photography.","The Pixel 8 uses Google's Tensor G3 processor with a 6.2-inch OLED display and a dual-camera system backed by Google's computational photography. It is a useful reference point for comparing compact Android phones, camera processing and Pixel software features.",{"display":"6.2-inch Actua OLED, 120Hz","chip":"Google Tensor G3","ram":"8GB","rear_camera":"50MP wide + 12MP ultrawide","os":"Android"},"https://store.google.com/us/product/pixel_8_specs"),
("Google","Pixel 8 Pro","google-pixel-8-pro","Google Pixel 8 Pro specifications, Tensor G3, LTPO OLED, 50MP triple camera and temperature sensor.","The Pixel 8 Pro is Google's larger 2023 flagship with Tensor G3, a high-refresh LTPO OLED display and a triple rear camera system. Its Pixel software, computational photography and AI features make it a strong comparison target for premium Android devices.",{"display":"6.7-inch Super Actua LTPO OLED, 1-120Hz","chip":"Google Tensor G3","ram":"12GB","rear_camera":"50MP + 48MP ultrawide + 48MP telephoto","os":"Android"},"https://store.google.com/us/product/pixel_8_pro_specs"),
("Google","Pixel 8a","google-pixel-8a","Google Pixel 8a specifications, Tensor G3, 120Hz OLED display, dual cameras and Pixel AI features.","The Pixel 8a brings Google's Tensor G3 platform and Pixel camera processing to a more affordable model. Its 120Hz OLED display, dual cameras and clean Android software make it relevant for buyers comparing value-focused camera phones.",{"display":"6.1-inch Actua OLED, 120Hz","chip":"Google Tensor G3","ram":"8GB","rear_camera":"64MP wide + 13MP ultrawide","os":"Android"},"https://store.google.com/us/product/pixel_8a_specs"),
("OnePlus","OnePlus 11","oneplus-11","OnePlus 11 specifications, Snapdragon 8 Gen 2, QHD+ LTPO display, Hasselblad cameras and 5000mAh battery.","The OnePlus 11 combines Snapdragon 8 Gen 2 performance with a high-resolution LTPO AMOLED display and a Hasselblad-branded camera system. Its large battery and fast charging make it a useful performance and value comparison phone.",{"display":"6.7-inch QHD+ LTPO, 1-120Hz","chip":"Snapdragon 8 Gen 2","battery":"5000mAh","rear_camera":"50MP + 32MP telephoto + 48MP ultrawide","os":"OxygenOS / Android"},"https://www.oneplus.com/global/11/specs"),
("OnePlus","OnePlus Nord CE4","oneplus-nord-ce4","OnePlus Nord CE4 specifications, Snapdragon 7 Gen 3, 120Hz AMOLED display and 5500mAh battery.","The OnePlus Nord CE4 focuses on value, combining Snapdragon 7 Gen 3 performance, a 120Hz AMOLED display, a large battery and fast charging. It is useful for comparisons centered on everyday speed, battery endurance and mid-range pricing.",{"display":"6.7-inch AMOLED, 120Hz","chip":"Snapdragon 7 Gen 3","battery":"5500mAh","charging":"100W SUPERVOOC","os":"OxygenOS / Android"},"https://www.oneplus.com/global/nord-ce4/specs"),
("Xiaomi","Xiaomi 14","xiaomi-14","Xiaomi 14 specifications, Snapdragon 8 Gen 3, LTPO AMOLED display and Leica triple cameras.","The Xiaomi 14 is a compact flagship built around Snapdragon 8 Gen 3 and a high-refresh AMOLED display. Its Leica-tuned triple-camera system and fast charging make it relevant for buyers comparing compact premium Android phones.",{"display":"6.36-inch LTPO AMOLED, 1-120Hz","chip":"Snapdragon 8 Gen 3","rear_camera":"Leica 50MP triple camera","battery":"4610mAh","os":"HyperOS / Android"},"https://www.mi.com/global/xiaomi-14/"),
("Xiaomi","Xiaomi 14 Ultra","xiaomi-14-ultra","Xiaomi 14 Ultra specifications, Snapdragon 8 Gen 3, Leica quad cameras and high-resolution LTPO AMOLED display.","The Xiaomi 14 Ultra is a camera-focused flagship with Snapdragon 8 Gen 3, a high-resolution LTPO AMOLED display and Leica-branded quad cameras. Its photography hardware and fast charging make it a natural comparison against premium camera phones.",{"display":"6.73-inch LTPO AMOLED, 1-120Hz","chip":"Snapdragon 8 Gen 3","rear_camera":"Leica 50MP quad-camera system","battery":"5000mAh","os":"HyperOS / Android"},"https://www.mi.com/global/xiaomi-14-ultra/"),
("Xiaomi","Xiaomi 14T","xiaomi-14t","Xiaomi 14T specifications, high-refresh AMOLED display, MediaTek Dimensity platform and Leica cameras.","The Xiaomi 14T targets upper mid-range buyers with a high-refresh AMOLED display, MediaTek Dimensity performance and Leica camera features. It offers a useful balance for users comparing display quality, photography and battery performance.",{"display":"6.67-inch AMOLED, 144Hz-class","chip":"MediaTek Dimensity flagship-class platform","rear_camera":"Leica triple camera","os":"HyperOS / Android"},"https://www.mi.com/global/xiaomi-14t/"),
("Xiaomi","Xiaomi 14T Pro","xiaomi-14t-pro","Xiaomi 14T Pro specifications, Dimensity 9300+, AMOLED 144Hz display and Leica camera system.","The Xiaomi 14T Pro combines a flagship-class MediaTek platform with a high-refresh AMOLED display and Leica camera tuning. Its fast charging and performance-focused hardware make it a strong value-oriented premium Android comparison.",{"display":"6.67-inch AMOLED, 144Hz","chip":"MediaTek Dimensity 9300+","rear_camera":"Leica triple camera","battery":"5000mAh-class","os":"HyperOS / Android"},"https://www.mi.com/global/xiaomi-14t-pro/"),
("Xiaomi","Redmi Note 14 Pro+ 5G","redmi-note-14-pro-plus-5g","Redmi Note 14 Pro+ 5G specifications, curved AMOLED display, high-resolution camera and large battery.","The Redmi Note 14 Pro+ 5G is a feature-rich mid-range phone emphasizing a high-resolution AMOLED display, 5G connectivity, camera hardware and fast charging. It is useful for comparing value smartphones across display, battery and camera categories.",{"display":"6.67-inch AMOLED, high refresh rate","chip":"Qualcomm Snapdragon platform","battery":"5000mAh-class","rear_camera":"200MP-class main camera","connectivity":"5G","os":"HyperOS / Android"},"https://www.mi.com/global/product/redmi-note-14-pro-plus-5g/"),
("POCO","POCO F6","poco-f6","POCO F6 specifications, Snapdragon 8s Gen 3, 120Hz AMOLED display and 5000mAh battery.","The POCO F6 is a performance-focused value phone using Snapdragon 8s Gen 3 and a high-refresh AMOLED display. Its large battery and fast charging make it particularly relevant for gaming and performance comparisons.",{"display":"6.67-inch AMOLED, 120Hz","chip":"Snapdragon 8s Gen 3","battery":"5000mAh","charging":"90W","os":"HyperOS / Android"},"https://www.po.co/global/product/poco-f6/"),
("POCO","POCO F6 Pro","poco-f6-pro","POCO F6 Pro specifications, Snapdragon 8 Gen 2, WQHD+ AMOLED display and 120W charging.","The POCO F6 Pro combines Snapdragon 8 Gen 2 performance with a high-resolution WQHD+ AMOLED display and very fast charging. It is aimed at users who prioritize gaming, sustained performance and display quality.",{"display":"6.67-inch WQHD+ AMOLED, 120Hz","chip":"Snapdragon 8 Gen 2","battery":"5000mAh","charging":"120W","os":"HyperOS / Android"},"https://www.po.co/global/product/poco-f6-pro/"),
("OPPO","Find X7 Ultra","oppo-find-x7-ultra","OPPO Find X7 Ultra specifications, Snapdragon 8 Gen 3, dual periscope cameras and Hasselblad camera tuning.","The OPPO Find X7 Ultra is a camera-centric flagship built around Snapdragon 8 Gen 3 and a multi-camera system with dual periscope telephoto hardware. Its premium display and fast charging make it relevant for high-end Android comparisons.",{"display":"6.82-inch AMOLED, 1-120Hz","chip":"Snapdragon 8 Gen 3","rear_camera":"Dual periscope quad-camera system","battery":"5000mAh","os":"ColorOS / Android"},"https://www.oppo.com/en/smartphones/series-find-x/find-x7-ultra/specs/"),
("OPPO","Reno13 Pro","oppo-reno13-pro","OPPO Reno13 Pro specifications, AMOLED display, high-resolution portrait camera and fast charging.","The OPPO Reno13 Pro is a premium mid-range phone emphasizing portrait photography, a smooth AMOLED display and fast charging. It is useful for comparisons focused on camera features, design and everyday battery performance.",{"display":"6.83-inch AMOLED, 120Hz-class","chip":"MediaTek Dimensity platform","rear_camera":"50MP-class main + telephoto + ultrawide","battery":"5800mAh-class","os":"ColorOS / Android"},"https://www.oppo.com/en/smartphones/series-reno/reno13-pro/"),
("vivo","X100 Pro","vivo-x100-pro","vivo X100 Pro specifications, Dimensity 9300, ZEISS cameras, 1-inch-class main sensor and fast charging.","The vivo X100 Pro is a photography-focused flagship using a MediaTek Dimensity 9300 platform and ZEISS-branded camera system. Its large main sensor, telephoto capability and fast charging make it a strong camera-phone comparison target.",{"display":"6.78-inch AMOLED, 120Hz","chip":"MediaTek Dimensity 9300","rear_camera":"ZEISS triple camera with 1-inch-class main sensor","battery":"5400mAh","os":"Funtouch OS / Android"},"https://www.vivo.com/en/products/x100-pro"),
("vivo","X100","vivo-x100","vivo X100 specifications, Dimensity 9300, 120Hz AMOLED display and ZEISS triple cameras.","The vivo X100 combines Dimensity 9300 performance with a high-refresh AMOLED display and ZEISS camera tuning. It offers a balanced flagship package for users comparing photography, performance and battery life.",{"display":"6.78-inch AMOLED, 120Hz","chip":"MediaTek Dimensity 9300","rear_camera":"ZEISS triple camera","battery":"5000mAh-class","os":"Funtouch OS / Android"},"https://www.vivo.com/en/products/x100"),
("realme","GT 6","realme-gt-6","realme GT 6 specifications, Snapdragon 8s Gen 3, LTPO AMOLED display and 5500mAh battery.","The realme GT 6 is a performance-oriented Android phone pairing Snapdragon 8s Gen 3 with a high-brightness LTPO AMOLED display and a large battery. It is useful for comparing value flagships and gaming-focused hardware.",{"display":"6.78-inch LTPO AMOLED, 120Hz","chip":"Snapdragon 8s Gen 3","battery":"5500mAh","charging":"120W","os":"realme UI / Android"},"https://www.realme.com/global/realme-gt-6"),
("realme","GT 6T","realme-gt-6t","realme GT 6T specifications, Snapdragon 7+ Gen 3, 120Hz LTPO AMOLED display and 5500mAh battery.","The realme GT 6T targets the upper mid-range performance segment with Snapdragon 7+ Gen 3, a 120Hz LTPO AMOLED display and fast charging. It is a useful benchmark for gaming and battery-focused buyers.",{"display":"6.78-inch LTPO AMOLED, 120Hz","chip":"Snapdragon 7+ Gen 3","battery":"5500mAh","charging":"120W","os":"realme UI / Android"},"https://www.realme.com/global/realme-gt-6t"),
("Sony","Xperia 1 VI","sony-xperia-1-vi","Sony Xperia 1 VI specifications, Snapdragon 8 Gen 3, 6.5-inch OLED display and telephoto camera.","The Xperia 1 VI is Sony's premium Android phone with Snapdragon 8 Gen 3, a high-quality OLED display and a versatile telephoto camera. Sony's camera, audio and display controls make it distinctive for enthusiast users.",{"display":"6.5-inch OLED, up to 120Hz","chip":"Snapdragon 8 Gen 3","rear_camera":"48MP main + ultrawide + telephoto","battery":"5000mAh","os":"Android"},"https://www.sony.com/electronics/smartphones/xperia-1-vi"),
("Sony","Xperia 10 VI","sony-xperia-10-vi","Sony Xperia 10 VI specifications, Snapdragon 6 Gen 1, OLED display, dual cameras and 5000mAh battery.","The Xperia 10 VI is a mid-range Sony phone emphasizing battery life, OLED viewing and a lightweight design. Its dual-camera setup and long-use orientation make it relevant to practical Android comparisons.",{"display":"6.1-inch OLED, 60Hz","chip":"Snapdragon 6 Gen 1","rear_camera":"48MP + 8MP ultrawide","battery":"5000mAh","os":"Android"},"https://www.sony.com/electronics/smartphones/xperia-10-vi"),
("ASUS","Zenfone 11 Ultra","asus-zenfone-11-ultra","ASUS Zenfone 11 Ultra specifications, Snapdragon 8 Gen 3, LTPO AMOLED display and 5500mAh battery.","The Zenfone 11 Ultra is a large premium ASUS phone with Snapdragon 8 Gen 3, a smooth LTPO AMOLED display and a high-capacity battery. Its performance and camera stabilization features make it useful for flagship comparisons.",{"display":"6.78-inch LTPO AMOLED, 1-120Hz","chip":"Snapdragon 8 Gen 3","battery":"5500mAh","rear_camera":"50MP main + 32MP telephoto + 13MP ultrawide","os":"Android"},"https://www.asus.com/mobile-handhelds/phones/zenfone/zenfone-11-ultra/"),
("ASUS","ROG Phone 8 Pro","asus-rog-phone-8-pro","ASUS ROG Phone 8 Pro specifications, Snapdragon 8 Gen 3, 165Hz AMOLED display and gaming features.","The ROG Phone 8 Pro is designed for mobile gaming, pairing Snapdragon 8 Gen 3 with a high-refresh AMOLED display, large battery and gaming controls. Its thermal and accessory ecosystem makes it distinct from conventional flagship phones.",{"display":"6.78-inch AMOLED, up to 165Hz","chip":"Snapdragon 8 Gen 3","battery":"5500mAh","rear_camera":"50MP main + 32MP telephoto + 13MP ultrawide","os":"Android"},"https://rog.asus.com/phones/rog-phone-8-pro/"),
("HONOR","Magic V3","honor-magic-v3","HONOR Magic V3 specifications, Snapdragon 8 Gen 3, foldable OLED displays and thin book-style design.","The HONOR Magic V3 is a thin book-style foldable built around Snapdragon 8 Gen 3 and dual OLED displays. Its lightweight foldable construction, large inner screen and multi-camera hardware make it relevant to premium foldable comparisons.",{"chip":"Snapdragon 8 Gen 3","display":"Foldable OLED dual-display system","rear_camera":"Triple camera with telephoto","form_factor":"Book-style foldable","os":"MagicOS / Android"},"https://www.honor.com/global/phones/honor-magic-v3/"),
("HONOR","200 Pro","honor-200-pro","HONOR 200 Pro specifications, Snapdragon 8s Gen 3, OLED display and portrait-focused camera system.","The HONOR 200 Pro is a camera-focused upper mid-range phone with Snapdragon 8s Gen 3, a high-refresh OLED display and portrait photography features. It is useful for comparing camera-centric phones below the ultra-premium tier.",{"display":"6.78-inch OLED, 120Hz","chip":"Snapdragon 8s Gen 3","battery":"5200mAh-class","rear_camera":"50MP main + telephoto + ultrawide","os":"MagicOS / Android"},"https://www.honor.com/global/phones/honor-200-pro/"),
("Motorola","Edge 50 Ultra","motorola-edge-50-ultra","Motorola Edge 50 Ultra specifications, Snapdragon 8s Gen 3, pOLED 144Hz display and 125W charging.","The Motorola Edge 50 Ultra combines Snapdragon 8s Gen 3 performance with a high-refresh pOLED display, fast charging and a versatile camera system. Its clean Android experience and premium design make it useful in upper mid-range comparisons.",{"display":"6.67-inch pOLED, 144Hz","chip":"Snapdragon 8s Gen 3","battery":"4500mAh-class","charging":"125W","os":"Android"},"https://www.motorola.com/us/smartphones-motorola-edge-50-ultra/p"),
("Motorola","Razr 50 Ultra","motorola-razr-50-ultra","Motorola Razr 50 Ultra specifications, Snapdragon 8s Gen 3, large cover display and foldable pOLED screen.","The Razr 50 Ultra is Motorola's premium clamshell foldable, combining Snapdragon 8s Gen 3 with a large external display and a foldable pOLED main screen. It is designed for users who want a compact foldable without giving up flagship-style features.",{"display":"6.9-inch foldable pOLED, 165Hz-class","chip":"Snapdragon 8s Gen 3","battery":"4000mAh-class","form_factor":"Clamshell foldable","os":"Android"},"https://www.motorola.com/us/smartphones-motorola-razr-50-ultra/p"),
("Nothing","Phone (2a) Plus","nothing-phone-2a-plus","Nothing Phone (2a) Plus specifications, MediaTek Dimensity 7350 Pro, 120Hz AMOLED display and dual cameras.","The Nothing Phone (2a) Plus is a mid-range Android phone emphasizing a clean interface, distinctive design and a high-refresh AMOLED display. Its MediaTek platform, dual camera system and Glyph-inspired design language make it a useful value comparison.",{"display":"6.7-inch AMOLED, 120Hz","chip":"MediaTek Dimensity 7350 Pro","battery":"5000mAh","rear_camera":"50MP dual camera","os":"Nothing OS / Android"},"https://nothing.tech/pages/phone-2a-plus"),
("Nothing","CMF Phone 1","cmf-phone-1","CMF Phone 1 specifications, MediaTek Dimensity 7300, 120Hz AMOLED display and 5000mAh battery.","The CMF Phone 1 is a value-oriented Android model with a 120Hz AMOLED display, MediaTek Dimensity 7300 and a large battery. Its modular-inspired design and competitive hardware make it useful for entry-level and mid-range comparisons.",{"display":"6.67-inch AMOLED, 120Hz","chip":"MediaTek Dimensity 7300","battery":"5000mAh","rear_camera":"50MP main + depth sensor","os":"Nothing OS / Android"},"https://cmf.tech/pages/phone-1"),
("Huawei","Mate 70 Pro","huawei-mate-70-pro","Huawei Mate 70 Pro specifications, OLED display, multi-camera system and HarmonyOS ecosystem.","The Huawei Mate 70 Pro is a premium Huawei smartphone centered on a high-quality OLED display, advanced camera hardware and the HarmonyOS ecosystem. Regional software, services and network compatibility can differ significantly, so Huawei's local product information should be checked.",{"display":"OLED high-refresh display","rear_camera":"Advanced multi-camera system","os":"HarmonyOS","form_factor":"Premium flagship"},"https://consumer.huawei.com/en/phones/mate70-pro/"),
("Huawei","Pura 70 Pro","huawei-pura-70-pro","Huawei Pura 70 Pro specifications, OLED display, high-resolution camera system and premium design.","The Huawei Pura 70 Pro focuses on mobile photography, premium industrial design and a high-quality OLED display. Its camera processing and Huawei software ecosystem make it a useful alternative in camera-phone comparisons, subject to regional service availability.",{"display":"OLED high-refresh display","rear_camera":"High-resolution multi-camera system","battery":"5000mAh-class","os":"HarmonyOS"},"https://consumer.huawei.com/en/phones/pura70-pro/"),
("nubia","Z70 Ultra","nubia-z70-ultra","nubia Z70 Ultra specifications, flagship Snapdragon platform, large AMOLED display and under-display camera design.","The nubia Z70 Ultra is a performance-focused flagship with a large AMOLED display and a distinctive under-display front-camera approach. Its high-end processor and large battery make it relevant for gaming, media and performance comparisons.",{"display":"Large AMOLED, high refresh rate","chip":"Snapdragon flagship platform","battery":"6000mAh-class","rear_camera":"Triple-camera system","os":"Android / MyOS"},"https://intl.nubia.com/products/nubia-z70-ultra"),
("REDMAGIC","10 Pro","redmagic-10-pro","REDMAGIC 10 Pro specifications, Snapdragon 8 Elite, 144Hz AMOLED display, active cooling and gaming controls.","The REDMAGIC 10 Pro is a gaming-focused Android phone with a flagship Snapdragon platform, high-refresh AMOLED display, active cooling and dedicated gaming controls. It is designed for sustained performance rather than conventional camera-first use.",{"display":"6.85-inch AMOLED, 144Hz","chip":"Snapdragon 8 Elite","battery":"7050mAh-class","charging":"100W-class","os":"Android"},"https://global.redmagic.gg/pages/redmagic-10-pro"),
("Fairphone","Fairphone 5","fairphone-5","Fairphone 5 specifications, repairable modular design, OLED display, 5G and long software support.","The Fairphone 5 is designed around repairability, modular components and long-term software support rather than maximum benchmark performance. Its 5G connectivity, OLED display and replaceable-part philosophy make it distinctive for sustainability-focused buyers.",{"display":"6.46-inch OLED, 90Hz","chip":"Qualcomm QCM6490","battery":"4200mAh","connectivity":"5G","os":"Android"},"https://www.fairphone.com/en/fairphone-5/"),
("Nokia","X30 5G","nokia-x30-5g","Nokia X30 5G specifications, Snapdragon 695, 90Hz AMOLED display and recycled-material design.","The Nokia X30 5G is a mid-range 5G phone with a 90Hz AMOLED display, Snapdragon 695 platform and a design emphasizing recycled materials. It remains a useful reference for buyers comparing practical Android hardware and sustainability features.",{"display":"6.43-inch AMOLED, 90Hz","chip":"Snapdragon 695 5G","battery":"4200mAh","rear_camera":"50MP + 13MP ultrawide","os":"Android"},"https://www.hmd.com/en_int/nokia-x-30"),
]


def upgrade():
    conn = op.get_bind()
    for brand, model, slug, desc, content, specs, source_url in RAW:
        exists = conn.execute(sa.text("SELECT id FROM phone_catalog WHERE slug=:slug"), {"slug": slug}).first()
        if exists:
            continue
        conn.execute(sa.text("""INSERT INTO phone_catalog
        (brand,model,slug,short_description,content,image_url,release_date,price_usd,price_bdt,specs_json,status,seo_description,created_at,updated_at,published_at,source_name,source_url,source_checked_at,data_confidence)
        VALUES (:brand,:model,:slug,:desc,:content,NULL,NULL,NULL,NULL,:specs,'published',:seo,:created,:updated,:published,:source,:url,:checked,'official')"""), {
            "brand": brand, "model": model, "slug": slug, "desc": desc, "content": content,
            "specs": json.dumps(specs, ensure_ascii=False), "seo": desc, "created": CHECKED,
            "updated": CHECKED, "published": CHECKED, "source": brand, "url": source_url, "checked": CHECKED,
        })


def downgrade():
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM phone_catalog WHERE slug = ANY(:slugs)"), {"slugs": [x[2] for x in RAW]})
