"""Add a curated set of high-demand popular phones for broader global SEO coverage."""
from alembic import op
import sqlalchemy as sa
import json
from datetime import datetime

revision = "0030_popular_phone_coverage"
down_revision = "0029_phone_expansion"
branch_labels = None
depends_on = None

CHECKED = datetime(2026, 9, 9, 0, 0, 0)

PHONES = [
 {"brand":"Apple","model":"iPhone 16","slug":"iphone-16","desc":"Apple iPhone 16 specifications, OLED display, A18 chip, dual cameras, 5G and iOS features.","content":"The iPhone 16 is a mainstream recent Apple phone for buyers who want current iOS features, strong performance, a compact premium design and a capable dual-camera system. It is a useful reference point when comparing iPhone 16 with newer iPhone models and Android flagships.","specs":{"category":"Premium","display":"OLED","chip":"Apple A18","rear_camera":"Dual camera system","connectivity":"5G","os":"iOS"},"source":"Apple","url":"https://www.apple.com/iphone-16/"},
 {"brand":"Apple","model":"iPhone 15","slug":"iphone-15","desc":"Apple iPhone 15 specifications, Dynamic Island, OLED display, A16 Bionic chip, 48MP camera and USB-C.","content":"The iPhone 15 remains an important Apple model for users comparing value, camera quality, performance and USB-C connectivity. Its page helps visitors evaluate the iPhone 15 against newer generations and similarly priced Android phones.","specs":{"category":"Premium","display":"Super Retina XDR OLED","chip":"Apple A16 Bionic","rear_camera":"48MP main dual-camera system","connectivity":"5G","port":"USB-C","os":"iOS"},"source":"Apple","url":"https://www.apple.com/iphone-15/"},
 {"brand":"Apple","model":"iPhone 14","slug":"iphone-14","desc":"Apple iPhone 14 specifications, OLED display, A15 Bionic, dual cameras, 5G and iOS.","content":"The iPhone 14 is a widely searched Apple model and a useful lower-cost entry into the modern iPhone lineup. It remains relevant for searches around iPhone 14 price, specifications, camera performance and 5G support.","specs":{"category":"Premium","display":"Super Retina XDR OLED","chip":"Apple A15 Bionic","rear_camera":"Dual 12MP camera system","connectivity":"5G","os":"iOS"},"source":"Apple","url":"https://www.apple.com/iphone-14/"},
 {"brand":"Samsung","model":"Galaxy S25","slug":"samsung-galaxy-s25","desc":"Samsung Galaxy S25 specifications, Dynamic AMOLED 2X display, Snapdragon 8 Elite, triple cameras and 5G.","content":"The Galaxy S25 is a compact flagship Samsung phone built around high-end performance, an AMOLED display, versatile cameras and long-term Galaxy software support. It is a strong comparison target for iPhone and Pixel buyers.","specs":{"category":"Flagship","display":"Dynamic AMOLED 2X","chip":"Snapdragon 8 Elite for Galaxy","rear_camera":"Triple camera system","connectivity":"5G","os":"Android / One UI"},"source":"Samsung","url":"https://www.samsung.com/global/galaxy/galaxy-s25/"},
 {"brand":"Samsung","model":"Galaxy S24","slug":"samsung-galaxy-s24","desc":"Samsung Galaxy S24 specifications, Dynamic AMOLED 2X, flagship chipset, triple cameras, 5G and Galaxy AI.","content":"The Galaxy S24 is a major Samsung flagship generation with a compact form factor, high-quality AMOLED display, versatile cameras and Galaxy AI features. It remains useful for buyers comparing flagship performance at a lower generation price.","specs":{"category":"Flagship","display":"Dynamic AMOLED 2X","chip":"Snapdragon 8 Gen 3 / Exynos 2400 by market","rear_camera":"Triple camera system","connectivity":"5G","os":"Android / One UI"},"source":"Samsung","url":"https://www.samsung.com/global/galaxy/galaxy-s24/"},
 {"brand":"Samsung","model":"Galaxy A55 5G","slug":"samsung-galaxy-a55-5g","desc":"Samsung Galaxy A55 5G specifications, Super AMOLED display, Exynos chipset, multi-camera system and 5G.","content":"The Galaxy A55 5G is an important mid-range Samsung model for buyers who want a premium-looking build, AMOLED display, 5G and the One UI ecosystem without flagship pricing. It is especially useful for comparisons with Pixel, Redmi and OnePlus mid-range phones.","specs":{"category":"Mid-range","display":"Super AMOLED","chip":"Exynos 1480","rear_camera":"Triple camera system","connectivity":"5G","os":"Android / One UI"},"source":"Samsung","url":"https://www.samsung.com/global/galaxy/galaxy-a55-5g/"},
 {"brand":"Samsung","model":"Galaxy A35 5G","slug":"samsung-galaxy-a35-5g","desc":"Samsung Galaxy A35 5G specifications, Super AMOLED display, Exynos 1380, 50MP camera and 5G.","content":"The Galaxy A35 5G is a popular mid-range Samsung option with an AMOLED display, 5G connectivity and a versatile camera setup. Its dedicated page targets practical searches around specifications, price comparisons and Samsung A-series alternatives.","specs":{"category":"Mid-range","display":"Super AMOLED","chip":"Exynos 1380","rear_camera":"50MP triple camera system","connectivity":"5G","os":"Android / One UI"},"source":"Samsung","url":"https://www.samsung.com/global/galaxy/galaxy-a35-5g/"},
 {"brand":"Google","model":"Pixel 9","slug":"google-pixel-9","desc":"Google Pixel 9 specifications, Actua OLED display, Tensor G4, advanced Pixel cameras and Android.","content":"The Pixel 9 is a recent Google flagship with a strong emphasis on computational photography, clean Android software and Google's AI features. It is a useful comparison model for iPhone, Galaxy and other premium Android searches.","specs":{"category":"Flagship","display":"OLED Actua display","chip":"Google Tensor G4","rear_camera":"Dual Pixel camera system","connectivity":"5G","os":"Android"},"source":"Google Store","url":"https://store.google.com/product/pixel_9"},
 {"brand":"Google","model":"Pixel 9a","slug":"google-pixel-9a","desc":"Google Pixel 9a specifications, OLED display, Tensor G4, Pixel camera processing, 5G and Android.","content":"The Pixel 9a is a value-oriented Pixel designed for buyers who prioritize camera processing, clean Android software and Google's AI features at a lower price than flagship Pixel models. It is a useful alternative to Samsung A-series and other mid-range phones.","specs":{"category":"Value flagship","display":"pOLED / OLED","chip":"Google Tensor G4","rear_camera":"Dual Pixel camera system","connectivity":"5G","os":"Android"},"source":"Google Store","url":"https://store.google.com/product/pixel_9a"},
 {"brand":"OnePlus","model":"OnePlus 13","slug":"oneplus-13","desc":"OnePlus 13 specifications, LTPO AMOLED display, Snapdragon 8 Elite, Hasselblad cameras and large battery.","content":"The OnePlus 13 is a performance-focused flagship with a high-refresh LTPO AMOLED display, flagship Snapdragon platform, fast charging and a camera system developed with Hasselblad branding. It is a strong comparison target for Galaxy S Ultra, Pixel Pro and iPhone Pro models.","specs":{"category":"Flagship","display":"LTPO AMOLED","chip":"Snapdragon 8 Elite","rear_camera":"Triple Hasselblad camera system","battery":"Large-capacity battery","connectivity":"5G","os":"OxygenOS / Android"},"source":"OnePlus","url":"https://www.oneplus.com/global/oneplus-13"},
 {"brand":"OnePlus","model":"OnePlus 12","slug":"oneplus-12","desc":"OnePlus 12 specifications, 2K LTPO AMOLED display, Snapdragon 8 Gen 3, Hasselblad cameras and fast charging.","content":"The OnePlus 12 remains a relevant flagship for buyers comparing performance, display quality, camera capability and fast charging. It is useful for searches where users want flagship specifications without the newest-generation price.","specs":{"category":"Flagship","display":"LTPO AMOLED","chip":"Snapdragon 8 Gen 3","rear_camera":"Triple Hasselblad camera system","battery":"5400mAh-class battery","connectivity":"5G","os":"OxygenOS / Android"},"source":"OnePlus","url":"https://www.oneplus.com/global/oneplus-12"},
 {"brand":"Xiaomi","model":"Xiaomi 15","slug":"xiaomi-15","desc":"Xiaomi 15 specifications, LTPO AMOLED display, Snapdragon 8 Elite, Leica cameras and fast charging.","content":"The Xiaomi 15 is a compact premium flagship emphasizing performance, display quality and Leica-branded photography. It is relevant to searches comparing Xiaomi with Samsung Galaxy S-series, OnePlus and iPhone models.","specs":{"category":"Flagship","display":"LTPO AMOLED","chip":"Snapdragon 8 Elite","rear_camera":"Leica triple camera system","connectivity":"5G","os":"HyperOS / Android"},"source":"Xiaomi","url":"https://www.mi.com/global/product/xiaomi-15/"},
 {"brand":"Xiaomi","model":"Xiaomi 14","slug":"xiaomi-14","desc":"Xiaomi 14 specifications, LTPO AMOLED display, Snapdragon 8 Gen 3, Leica cameras and 5G.","content":"The Xiaomi 14 is a compact flagship known for its premium display, Snapdragon performance and Leica camera system. It remains useful for users comparing high-end Android phones across generations.","specs":{"category":"Flagship","display":"LTPO AMOLED","chip":"Snapdragon 8 Gen 3","rear_camera":"Leica triple camera system","connectivity":"5G","os":"HyperOS / Android"},"source":"Xiaomi","url":"https://www.mi.com/global/product/xiaomi-14/"},
 {"brand":"Redmi","model":"Redmi Note 14 Pro+ 5G","slug":"redmi-note-14-pro-plus-5g","desc":"Redmi Note 14 Pro+ 5G specifications, AMOLED display, high-resolution camera, 5G and fast charging.","content":"The Redmi Note 14 Pro+ 5G targets the feature-rich mid-range market with a high-quality AMOLED display, high-resolution camera hardware and fast charging. It is useful for buyers comparing Redmi Note with Samsung A-series, POCO and realme models.","specs":{"category":"Upper mid-range","display":"AMOLED","rear_camera":"High-resolution multi-camera system","connectivity":"5G","charging":"Fast charging","os":"HyperOS / Android"},"source":"Xiaomi","url":"https://www.mi.com/global/"},
 {"brand":"POCO","model":"POCO X7 Pro","slug":"poco-x7-pro","desc":"POCO X7 Pro specifications, high-refresh AMOLED display, Dimensity performance, large battery and fast charging.","content":"The POCO X7 Pro is a performance-oriented mid-range phone aimed at gaming and demanding everyday use. Its page helps capture searches around POCO X-series specifications and comparisons with Redmi, realme and OnePlus performance models.","specs":{"category":"Performance mid-range","display":"High-refresh AMOLED","chip":"MediaTek Dimensity performance platform","battery":"Large-capacity battery","connectivity":"5G","os":"HyperOS / Android"},"source":"POCO","url":"https://www.po.co/global/"},
 {"brand":"OPPO","model":"Reno 13 Pro","slug":"oppo-reno-13-pro","desc":"OPPO Reno 13 Pro specifications, AMOLED display, portrait-focused cameras, 5G and fast charging.","content":"The OPPO Reno 13 Pro is a camera-focused upper mid-range phone with a premium design, AMOLED display and fast charging. It is useful for comparisons with vivo V/X series, Samsung A-series and Xiaomi/Redmi models.","specs":{"category":"Upper mid-range","display":"AMOLED","rear_camera":"Multi-camera portrait-focused system","connectivity":"5G","charging":"Fast charging","os":"ColorOS / Android"},"source":"OPPO","url":"https://www.oppo.com/en/smartphones/series-reno/reno13-pro/"},
 {"brand":"vivo","model":"V50","slug":"vivo-v50","desc":"vivo V50 specifications, curved AMOLED display, ZEISS camera features, 5G and fast charging.","content":"The vivo V50 is a popular upper mid-range model focused on portrait photography, display quality and fast charging. It is a useful comparison point for buyers evaluating vivo against OPPO Reno, Samsung A-series and Redmi Note phones.","specs":{"category":"Upper mid-range","display":"Curved AMOLED","rear_camera":"ZEISS-branded dual-camera system","connectivity":"5G","charging":"Fast charging","os":"Android / Funtouch OS or regional equivalent"},"source":"vivo","url":"https://www.vivo.com/global/products"},
 {"brand":"realme","model":"GT 7 Pro","slug":"realme-gt-7-pro","desc":"realme GT 7 Pro specifications, LTPO AMOLED display, Snapdragon 8 Elite, large battery and fast charging.","content":"The realme GT 7 Pro is a performance flagship aimed at users who prioritize gaming, display quality, battery endurance and fast charging. It is a strong comparison target for OnePlus, POCO and Xiaomi performance phones.","specs":{"category":"Performance flagship","display":"LTPO AMOLED","chip":"Snapdragon 8 Elite","battery":"Large-capacity battery","charging":"Fast charging","connectivity":"5G","os":"realme UI / Android"},"source":"realme","url":"https://www.realme.com/global/"},
 {"brand":"Motorola","model":"Edge 50 Pro","slug":"motorola-edge-50-pro","desc":"Motorola Edge 50 Pro specifications, pOLED display, Snapdragon platform, 50MP camera and fast charging.","content":"The Motorola Edge 50 Pro is a premium mid-range Android phone combining a high-quality pOLED display, capable cameras and fast charging. It is relevant to buyers comparing Motorola with Samsung, Pixel and OnePlus alternatives.","specs":{"category":"Premium mid-range","display":"pOLED","chip":"Snapdragon 7 Gen 3","rear_camera":"50MP triple camera system","connectivity":"5G","charging":"Fast charging","os":"Android"},"source":"Motorola","url":"https://www.motorola.com/us/smartphones-motorola-edge"},
 {"brand":"HONOR","model":"HONOR 200 Pro","slug":"honor-200-pro","desc":"HONOR 200 Pro specifications, OLED display, Snapdragon platform, portrait camera system and fast charging.","content":"The HONOR 200 Pro is a camera-focused premium mid-range phone, particularly relevant to portrait photography and display searches. Its page provides another useful alternative to Samsung, Pixel, OPPO and vivo models.","specs":{"category":"Premium mid-range","display":"OLED","chip":"Snapdragon 8s Gen 3","rear_camera":"Triple camera system with portrait focus","connectivity":"5G","charging":"Fast charging","os":"MagicOS / Android"},"source":"HONOR","url":"https://www.honor.com/global/phones/honor-200-pro/"},
 {"brand":"Nothing","model":"Phone (2a)","slug":"nothing-phone-2a","desc":"Nothing Phone (2a) specifications, AMOLED display, MediaTek chipset, dual cameras, 5G and Nothing OS.","content":"Nothing Phone (2a) is a value-focused Android phone known for its distinctive design, clean Nothing OS experience and high-refresh AMOLED display. It is useful for buyers comparing design-led mid-range phones.","specs":{"category":"Mid-range","display":"AMOLED","chip":"MediaTek Dimensity platform","rear_camera":"Dual camera system","connectivity":"5G","os":"Nothing OS / Android"},"source":"Nothing","url":"https://nothing.tech/pages/phone-2a"},
 {"brand":"Sony","model":"Xperia 10 VI","slug":"sony-xperia-10-vi","desc":"Sony Xperia 10 VI specifications, OLED display, Snapdragon chipset, dual cameras, 5G and long battery life.","content":"The Xperia 10 VI is a mid-range Sony phone emphasizing battery endurance, multimedia use and Sony's clean Android experience. It is useful for users comparing Xperia models and creator-friendly alternatives.","specs":{"category":"Mid-range","display":"OLED","chip":"Snapdragon 6 Gen 1","rear_camera":"Dual camera system","battery":"5000mAh-class battery","connectivity":"5G","os":"Android"},"source":"Sony","url":"https://www.sony.com/electronics/smartphones/xperia-10-vi"},
]


def upgrade():
    conn = op.get_bind()
    for phone in PHONES:
        conn.execute(sa.text("""INSERT INTO phone_catalog
            (brand, model, slug, short_description, content, image_url, release_date,
             price_usd, price_bdt, specs_json, status, seo_description, created_at,
             updated_at, published_at, source_name, source_url, source_checked_at, data_confidence)
            VALUES (:brand, :model, :slug, :desc, :content, NULL, NULL, NULL, NULL,
                    :specs, 'published', :seo, :checked, :checked, :checked,
                    :source, :url, :checked, 'official')
            ON CONFLICT (slug) DO NOTHING"""), {
            "brand": phone["brand"], "model": phone["model"], "slug": phone["slug"],
            "desc": phone["desc"], "content": phone["content"],
            "specs": json.dumps(phone["specs"], ensure_ascii=False), "seo": phone["desc"],
            "source": phone["source"], "url": phone["url"], "checked": CHECKED,
        })


def downgrade():
    conn = op.get_bind()
    for phone in PHONES:
        conn.execute(sa.text("DELETE FROM phone_catalog WHERE slug=:slug"), {"slug": phone["slug"]})
